source 'http://rubygems.org'

<%= rails_gemfile_entry -%>
<%= database_gemfile_entry -%>
<%= "gem 'jruby-openssl'\n" if defined?(JRUBY_VERSION) -%>
<%= "gem 'json'\n" if RUBY_VERSION < "1.9.2" -%>
<%= javascript_gemfile_entry %>

gem 'coercion'
gem 'haml'

# To use ActiveModel has_secure_password
#gem 'bcrypt-ruby', '~> 3.0.0'

# Use unicorn as the web server
#gem 'unicorn'

# Deploy with Capistrano
#gem 'capistrano'

# To use debugger
#<%= ruby_debugger_gemfile_entry %>

<%= assets_gemfile_entry.gsub(/,\s+/, ', ') %>
<%= turn_gemfile_entry -%>
<%= rspec_gemfile_entry -%>
